coins = {'2GIVE': '2GIVE',
         'AMP': 'AMP',
         'AdEx': 'ADX',
         'Ada': 'ADA',
         'Aeon': 'AEON',
         'Apx': 'APX',
         'Aragon': 'ANT',
         'Ardor': 'ARDR',
         'Ark': 'ARK',
         'ArtByte': 'ABY',
         'Augur': 'REP',
         'AuroraCoin': 'AUR',
         'BURSTCoin': 'BURST',
         'Bancor': 'BNT',
         'Basic Attention Token': 'BAT',
         'BitBay': 'BAY',
         'BitBean': 'BITB',
         'BitCrystals': 'BCY',
         'BitSend': 'BSD',
         'Bitcoin Cash': 'BCC',
         'Bitcoin Gold': 'BTG',
         'BitcoinDark': 'BTCD',
         'Bitswift': 'SWIFT',
         'BlackCoin': 'BLK',
         'Blitzcash': 'BLITZ',
         'BlockNet': 'BLOCK',
         'Blocktix': 'TIX',
         'Breakout': 'BRK',
         'Breakout Stake': 'BRX',
         'Bytecent': 'BYC',
         'Bytes': 'GBYTE',
         'CLAMs': 'CLAM',
         'CannabisCoin': 'CANN',
         'CapriCoin': 'CPC',
         'Circuits of Value': 'COVAL',
         'Civic': 'CVC',
         'CloakCoin': 'CLOAK',
         'ClubCoin': 'CLUB',
         'Cofound.it': 'CFI',
         'Counterparty': 'XCP',
         'CreditBit': 'CRB',
         'Crown': 'CRW',
         'CureCoin': 'CURE',
         'DECENT': 'DCT',
         'Dash': 'DASH',
         'Databits': 'DTB',
         'Decentraland': 'MANA',
         'Decred': 'DCR',
         'Diamond': 'DMD',
         'Digibyte': 'DGB',
         'DigitalNote': 'XDN',
         'DigixDAO': 'DGD',
         'Dogecoin': 'DOGE',
         'DopeCoin': 'DOPE',
         'Dynamic': 'DYN',
         'Edgeless': 'EDG',
         'Einsteinium': 'EMC2',
         'Elastic': 'XEL',
         'ElectronicGulden': 'EFL',
         'EmerCoin': 'EMC',
         'EnergyCoin': 'ENRG',
         'Enigma': 'ENG',
         'Ethereum': 'ETH',
         'Ethereum Classic': 'ETC',
         'EuropeCoin': 'ERC',
         'EverGreenCoin': 'EGC',
         'ExclusiveCoin': 'EXCL',
         'Expanse': 'EXP',
         'Factom': 'FCT',
         'FairCoin': 'FAIR',
         'Feathercoin': 'FTC',
         'FirstBlood': '1ST',
         'Florin': 'FLO',
         'FoldingCoin': 'FLDC',
         'FunFair': 'FUN',
         'GBG': 'GBG',
         'Gambit': 'GAM',
         'GameCredits': 'GAME',
         'GeoCoin': 'GEO',
         'GlobalCurrencyReserve': 'GCR',
         'Gnosis': 'GNO',
         'GoldCoin': 'GLD',
         'Golem': 'GNT',
         'Golos': 'GOLOS',
         'GridCoin': 'GRC',
         'Groestlcoin': 'GRS',
         'Gulden': 'NLG',
         'Guppy': 'GUP',
         'HempCoin': 'THC',
         'Humaniq': 'HMQ',
         'I/OCoin': 'IOC',
         'IDNI Agoras': 'AGRS',
         'Incent': 'INCNT',
         'InfluxCoin': 'INFX',
         'Internet Of People': 'IOP',
         'Ion': 'ION',
         'Komodo': 'KMD',
         'Kore': 'KORE',
         'LBRY Credits': 'LBC',
         'Legends': 'LGD',
         'Lisk': 'LSK',
         'Litecoin': 'LTC',
         'Lomocoin': 'LMC',
         'Lumen': 'XLM',
         'Lunyr': 'LUN',
         'Magi': 'XMG',
         'MaidSafe': 'MAID',
         'Melon': 'MLN',
         'Memetic': 'MEME',
         'Mercury': 'MER',
         'Metal': 'MTL',
         'MonaCoin': 'MONA',
         'Monaco': 'MCO',
         'Monero': 'XMR',
         'MonetaryUnit': 'MUE',
         'Musicoin': 'MUSIC',
         'Myriad': 'XMY',
         'Mysterium': 'MYST',
         'NAVCoin': 'NAV',
         'NXT': 'NXT',
         'Neo': 'NEO',
         'NeosCoin': 'NEOS',
         'NewEconomyMovement': 'XEM',
         'Nexium': 'NXC',
         'Nexus': 'NXS',
         'Nubits': 'NBT',
         'Numeraire': 'NMR',
         'OMNI': 'OMNI',
         'OkCash': 'OK',
         'OmiseGO': 'OMG',
         'ParkByte': 'PKB',
         'Particl': 'PART',
         'Patientory': 'PTOY',
         'Peercoin': 'PPC',
         'PesetaCoin ': 'PTC',
         'PinkCoin': 'PINK',
         'Pivx': 'PIVX',
         'PotCoin': 'POT',
         'PowerLedger': 'POWR',
         'Project Decorum': 'PDC',
         'Qtum': 'QTUM',
         'Quantum Resistant Ledger': 'QRL',
         'Qwark': 'QWARK',
         'Radium': 'RADS',
         'ReddCoin': 'RDD',
         'Ripio Credit Network': 'RCN',
         'Ripple': 'XRP',
         'Rise': 'RISE',
         'RubyCoin': 'RBY',
         'STEEM': 'STEEM',
         'Salt': 'SALT',
         'SaluS': 'SLS',
         'Sequence': 'SEQ',
         'Shift': 'SHIFT',
         'Siacoin': 'SC',
         'Siberian Chervonets': 'SIB',
         'SingularDTV': 'SNGLS',
         'SolarCoin': 'SLR',
         'Sphere': 'SPHR',
         'SpreadCoin': 'SPR',
         'StartCoin': 'START',
         'Status Network Token': 'SNT',
         'StealthCoin': 'XST',
         'SteemDollars': 'SBD',
         'Storj': 'STORJ',
         'Stratis': 'STRAT',
         'Swarm City Token': 'SWT',
         'Syndicate': 'SYNX',
         'Synergy': 'SNRG',
         'SysCoin': 'SYS',
         'TRIG Token': 'TRIG',
         'TenX Pay Token': 'PAY',
         'Tokes': 'TKS',
         'TransferCoin': 'TX',
         'TrustPlus': 'TRUST',
         'Trustcoin': 'TRST',
         'Ubiq': 'UBQ',
         'UnbreakableCoin': 'UNB',
         'Vcash': 'XVC',
         'Verge': 'XVG',
         'VeriCoin': 'VRC',
         'Verium': 'VRM',
         'Vertcoin': 'VTC',
         'ViaCoin ': 'VIA',
         'Viberate': 'VIB',
         'Voxels': 'VOX',
         'Waves': 'WAVES',
         'WhiteCoin': 'XWC',
         'Wings DAO': 'WINGS',
         'Xaurum': 'XAUR',
         'ZCoin': 'XZC',
         'Zcash': 'ZEC',
         'Zclassic': 'ZCL',
         'Zencash': 'ZEN',
         'adToken': 'ADT',
         'district0x': 'DNT',
         'eBoost': 'EBST',
         'iEx.ec': 'RLC',
         'vTorrent': 'VTR'
         }

coins_abbr = [
    'LTC',
    'DOGE',
    'VTC',
    'PPC',
    'FTC',
    'RDD',
    'NXT',
    'DASH',
    'POT',
    'BLK',
    'EMC2',
    'XMY',
    'AUR',
    'EFL',
    'GLD',
    'SLR',
    'PTC',
    'GRS',
    'NLG',
    'RBY',
    'XWC',
    'MONA',
    'THC',
    'ENRG',
    'ERC',
    'VRC',
    'CURE',
    'XMR',
    'CLOAK',
    'START',
    'KORE',
    'XDN',
    'TRUST',
    'NAV',
    'XST',
    'BTCD',
    'VIA',
    'PINK',
    'IOC',
    'CANN',
    'SYS',
    'NEOS',
    'DGB',
    'BURST',
    'EXCL',
    'SWIFT',
    'DOPE',
    'BLOCK',
    'ABY',
    'BYC',
    'XMG',
    'BLITZ',
    'BAY',
    'FAIR',
    'SPR',
    'VTR',
    'XRP',
    'GAME',
    'COVAL',
    'NXS',
    'XCP',
    'BITB',
    'GEO',
    'FLDC',
    'GRC',
    'FLO',
    'NBT',
    'MUE',
    'XEM',
    'CLAM',
    'DMD',
    'GAM',
    'SPHR',
    'OK',
    'SNRG',
    'PKB',
    'CPC',
    'AEON',
    'ETH',
    'GCR',
    'TX',
    'BCY',
    'EXP',
    'INFX',
    'OMNI',
    'AMP',
    'AGRS',
    'XLM',
    'CLUB',
    'VOX',
    'EMC',
    'FCT',
    'MAID',
    'EGC',
    'SLS',
    'RADS',
    'DCR',
    'BSD',
    'XVG',
    'PIVX',
    'XVC',
    'MEME',
    'STEEM',
    '2GIVE',
    'LSK',
    'PDC',
    'BRK',
    'DGD',
    'WAVES',
    'RISE',
    'LBC',
    'SBD',
    'BRX',
    'ETC',
    'STRAT',
    'UNB',
    'SYNX',
    'TRIG',
    'EBST',
    'VRM',
    'SEQ',
    'XAUR',
    'SNGLS',
    'REP',
    'SHIFT',
    'ARDR',
    'XZC',
    'NEO',
    'ZEC',
    'ZCL',
    'IOP',
    'GOLOS',
    'UBQ',
    'KMD',
    'GBG',
    'SIB',
    'LMC',
    'QWARK',
    'CRW',
    'SWT',
    'MLN',
    'ARK',
    'DYN',
    'TKS',
    'MUSIC',
    'DTB',
    'INCNT',
    'GBYTE',
    'GNT',
    'NXC',
    'EDG',
    'LGD',
    'TRST',
    'WINGS',
    'RLC',
    'GNO',
    'GUP',
    'LUN',
    'APX',
    'HMQ',
    'ANT',
    'SC',
    'BAT',
    'ZEN',
    '1ST',
    'QRL',
    'CRB',
    'PTOY',
    'MYST',
    'CFI',
    'BNT',
    'NMR',
    'SNT',
    'DCT',
    'XEL',
    'MCO',
    'ADT',
    'FUN',
    'PAY',
    'MTL',
    'STORJ',
    'ADX',
    'OMG',
    'CVC',
    'PART',
    'QTUM',
    'BCC',
    'DNT',
    'ADA',
    'MANA',
    'SALT',
    'TIX',
    'RCN',
    'VIB',
    'MER',
    'POWR',
    'BTG',
    'ENG'
]
